project:
  type: website
  output-dir: docs

website:
  title: "Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data_cleaning.qmd
        text: Limpieza y preparación de los datos
      - href: visualizations.qmd
        text: Análisis y visualización

format:
  html:
    theme: cosmo
    toc: true